### ISSUE TITLE
How to handle NIST 800-53 sub elements?

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/discuss#22]
What is the appropriate way to document NIST 800-53 sub-elements in the component.yaml's?

In the FISMA guidance, we have controls with sub-elements. For example: AC-2

![image](https://cloud.githubusercontent.com/assets/5713754/24892066/eb43f8f2-1e47-11e7-804e-f9020bc84b94.png)

In the FedRAMP word templates, these sub-elements are broken out into tables:
![image](https://cloud.githubusercontent.com/assets/5713754/24892169/756a9342-1e48-11e7-9268-dd6e9a4900da.png)

In code I can do something like this:
`````
- control_key: AC-2
  standard_key: NIST-800-53
  covered_by: []
  implimentation_status: none
  narrative:
   - text: |
        (a) some answer A

        (b) some answer for B
`````

..... however, using fedramp-templater, these sub-elements do not get properly populated. Anyone tackle this yet?

**Comment by shawndwells** [comment]
Closest I've seen in code was from AWS:
https://github.com/opencontrol/aws-compliance/blob/master/EC2/component.yaml#L11

`````
- control_key: SC-7
  covered_by: []
  implementation_status: none
  narrative: "#### a  \nThe AWS network provides significant protection against traditional\
    \ network security issues, and 18F can implement further protection. The following\
`````

Tried breaking elements out such as "#### a" and "#### b" to no avail

**Comment by JJediny** [comment]
@shawndwells the `key` attribute is a sub-element which is currently supported by Compliance Masonry .doc/docx output:

```
  - control_key: AC-2 (7)
    covered_by: []
    implementation_status: complete
    control_origin: "service provider system specific"
    narrative:
      - key: a
        text: |
          'example
          ...'
    standard_key: NIST-800-53
```
