### ISSUE TITLE
Parameterized includes of sub components

### ISSUE THREAD

**Issue by cmc333333** [opencontrol/discuss#4]
Consider tools like Gemnasium, Quantified Code, and Travis -- each covers some component of the compliance process. However, adding a verification for each requires adding a unique URL (i.e. pointing to the project page within Gemnasium, QC, Travis). It'd be handy if we could define component docs for each of these tools once and re-use them across projects, but there's no way to template that URL/project id/etc. One potential approach would be to add something to the `opencontrol.yaml` file:

``` yaml
dependencies:
    systems:
    - url: https://path/to/travis/docs
      parameters:
          badge: https://travis.thing/image/myproject
```
