### ISSUE TITLE
subdirectory structures in component repos

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/discuss#41]
In the current RedHat content repo, directory structure is used to breakout products:

https://github.com/opencontrol/RedHat/tree/master/OpenShift-v3
https://github.com/opencontrol/RedHat/tree/master/OpenStackPlatform

If I understand the OpenControl schema for ``systems`` correctly, only ``url`` and ``revision`` can be passed as arguments:

https://github.com/opencontrol/schemas/blob/master/kwalify/opencontrol/v1.0.0.yaml#L53#L61
`````
      systems:
        type: seq
        sequence:
          - type: map
            mapping:
              url:
                type: str
              revision:
                type: str
`````

This forces us to create many content repos, e.g. redhat-rhel, redhat-openshift, redhat-jboss, instead of one per vendor. 

Has there been a discussion on if this is desired? Should we update the schema to support a directory tree, e.g.:
`````
  systems:
    - url: https://github.com/opencontrol/RedHat
      revision: master
      folder: tree/master/Product1
    - url: https://github.com/opencontrol/RedHat
      revision: master
      folder: tree/master/Product2
`````
