### ISSUE TITLE
One component control definition to implement multiple standards controls?

### ISSUE THREAD

**Issue by riskpeep** [opencontrol/discuss#48]
In component.yaml, we define controls.  Each control has a 'standard_key' and a 'control_key' and (among other things) a 'narrative' section.

Is it possible to have one component control definition to implement multiple standards' controls so that one narrative section could be used to satisfy the control requirements for multiple standards?  Or one control that implements multiple required controls w/in one standard.

I've tried putting in multiple 'standard_key' and 'control_key' sections and that doesn't appear to work, I only get one section in the output document.

**Comment by shawndwells** [comment]
Have been playing with this too. For example to add PCI-DSS mappings to NIST 800-53 control responses... don't want to create entirely separate bodies of work for each standard.

Some example code of having PCI-DSS and NIST 800-53 in the same response:
https://github.com/opencontrol/schemas/blob/master/examples/component_v3.1.0.yaml

That approach still requires copy/pasting responses to map against multiple standards. Have been debating about restructuring a new component schema to something like this:

(answer for PCI-DSS control 1.1, but also maps answer to NIST 800-53 AU-5 and CM-6)

`````
  - control_key: 1.1
    implementation_status: partial
    parameters:
      - key: "a"
        text: "Parameter A for 1.1"
      - key: "b"
        text: "Parameter B for 1.1"
    narrative:
      - key: "a"
        text: "Justification in narrative form A for 1.1"
      - key: "b"
        text: "Justification in narrative form B for 1.1"
    standard_key: PCI-DSS-MAY-2015
    standard_mappings:
      - control: AU-5
      - control: CM-6
`````
