### ISSUE TITLE
docs gitbook: Component files does not exist

### ISSUE THREAD

**Issue by git-ingham** [opencontrol/discuss#51]
I am trying to produce a PDF version of SSP.  I have an opencontrol.yaml that passes the schema test.
However:
```
$ compliance-masonry docs gitbook NIST-SP-800-171r1_all
An error occurred: Component files does not exist
```
That is an unhelpful error message.  Which of the yaml files is missing the "files" component?  Or am I misreading the error and there are missing "component files"?  How can I track it to the problem that needs fixing?  I would prefer to not be reading all the source code to track it down.  I did use strace; the error shows up right after a child exited.  Shortly before that, something tried to do an epoll_ctl that failed due to EPERM (Operation not permitted).  The file it was trying to work with was /dev/null.  Not sure how helpful this information is.

Is it even worth trying to use gitbook? I ran across [this thread](https://github.com/GitbookIO/gitbook/issues/1808).  If not, the documentation for compliance-masonry should be updated to not point to it (side note, the "Usage" section of compliance-masonry is weak).

Or, is there a better way to produce a PDF?  I am also going to look at ssptool (maybe its reports will be my solution).

**Comment by shawndwells** [comment]
This appears to be a legitimate bug. The ``docs gitbook`` subroutine appears to be looking for the old masonry output structure.

+cc @redhatrises

To duplicate, here's an opencontrol.yaml:
`````
schema_version: "1.0.0"
name: Template Information System
metadata:
  description: Template Information System
  maintainers:
    - Shawn Wells <shawn@redhat.com>

components:
#    - ./../../ComplianceAsCode/redhat-openstack-platform-13
#    - ./../../ComplianceAsCode/redhat-openshift-v3
#    - ./../../ComplianceAsCode/redhat/ansible-tower

dependencies:
  standards:
    - url: https://github.com/opencontrol/standards
      revision: master
  certifications:
    - url: https://github.com/opencontrol/certifications
      revision: master
  systems:
#    - url: https://github.com/SecurityCentral/template-system-process-controls
#      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: osp13
      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: ocp3
      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: idm
      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: ansible-tower
      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: rhvm
      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: rhvh
      revision: opencontrol
`````

Then run ``masonry get``:
``$ masonry get``

Which will create:
`````
	opencontrols/components/ansible-tower.yaml
	opencontrols/components/idm.yaml
	opencontrols/components/ocp3.yaml
	opencontrols/components/osp13.yaml
	opencontrols/components/rhvh.yaml
	opencontrols/components/rhvm.yaml
`````

The ``docs gitbook`` needs to be updated NOT to use opencontrols/components/<component-name>/component.yaml
